# Permalinks
permalink:            pretty

# Setup
title:                'Lukas Rammelmüller'
description:          'postdoc @ LMU Munich'
baseurl:              /

author:
  name:               'Lukas Rammelmüller'
  url:
