# Permalinks
permalink:            pretty

# Setup
title:                'Lukas Rammelmüller'
description:          'PhD candidate @ TU Darmstadt'
baseurl:              /

author:
  name:               'Lukas Rammelmüller'
  url:
