# Dependencies
highlighter:          pygments

# Permalinks
permalink:            pretty

# Setup
title:                'Lukas Rammelmüller'
description:          'PhD candidate @ TU Darmstadt'
baseurl:              /

author:
  name:               'Lukas Rammelmüller'
  url:

# Custom vars.
updated:              'May 2019'
footer:               'Build with Jekyll and <span class="love">❤</span> <br>Based on the hyde and poole themes.'
